### ISSUE TITLE
feat: create service

### ISSUE THREAD

**Issue by wsameer** [medly/starter#48]
### Description

We want to create a boilerplate/starter project for quickly building RESTful APIs using Node.js and [Express](https://expressjs.com/) framework.

The philosophy is to create a Node.js app with minimal code which is production ready.

### Solution you'd like

- Create a command - `yarn create @medly/service <project-name> [options]` to initiate the service's installation process.
- By running this command you should get a production-ready Node.js app installed and fully configured on your machine.
- The command should support the following 3 package managers:

	| Package Manager | Command |
	|----|----|
	|  NPM | `npm init @medly/service` |
	|  Yarn | `yarn create @medly/service` |
	|  PNPM | `pnpx @medly/service` |

- The command should accept the following optional flags
 
	| Flags | Description | Choices | Default |
	| ----- | ----------- | ------- | ------- |
	| `-V, --version` | output the version number | | |
	| `-pm, --package-manager <package-manager>` | package manager | `npm`, `yarn`, `pnpm`     | `yarn`  |
	| `-p, --port <language>` | port | [valid port numbers] | 3000 |
	| `-l, --language <language>` | language | `typescript`, `javascript` | `typescript` |
	| `-i, --interactive` | show interactive questionnaire | | |
	| `-h, --help` | display help for command       | | |

- The service should have 100% tests coverage using [Jest](https://jestjs.io/docs/getting-started) and [Supertest](https://github.com/visionmedia/supertest).
- By default, we want the service to be build using TypeScript.
- The server should start be default on 3000 port.

###  The service should provide the following features
- CORS enabled
- Uses  [helmet](https://github.com/helmetjs/helmet)  to set some HTTP headers for security
-   Gzip compression with  [compression](https://github.com/expressjs/compression)
-   Linting with  [eslint](http://eslint.org/)
-  Git hooks with  [husky](https://github.com/typicode/husky)
-   Logging with  [morgan](https://github.com/expressjs/morgan)

### Additional context

Follow the directory structure and code given in [express-typescript-boilerplate](https://github.com/medly/express-typescript-boilerplate) and provide the same experience.

**Comment by gmukul01** [comment]
Covered in #52
